apiVersion: apps/v1
kind: Deployment
metadata:
  name: Exhibition
  labels:
    app: Exhibition
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Exhibition
  template:
    metadata:
      labels:
        app: Exhibition
    spec:
      containers:
        - name: Exhibition
          image: username/Exhibition:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5